// Each sensor declares its own normal range and warning bands.
// Anything inside `normalRange` is "normal"; inside a `warningBands` tuple is
// "warning"; anything else within [min, max] is "critical". This single shape
// drives simulation, status evaluation, gauges, and cards generically.
export const SENSORS = [
  {
    key: 'engineTemp',
    label: 'Engine Temperature',
    icon: '🌡️',
    unit: '°C',
    min: 0,
    max: 150,
    baseline: 85,
    fluctuation: 8,
    normalRange: [70, 100],
    warningBands: [[60, 70], [100, 110]],
  },
  {
    key: 'oilTemp',
    label: 'Oil Temperature',
    icon: '🛢️',
    unit: '°C',
    min: 0,
    max: 160,
    baseline: 95,
    fluctuation: 6,
    normalRange: [80, 110],
    warningBands: [[70, 80], [110, 125]],
  },
  {
    key: 'brakePadWear',
    label: 'Brake Pad Wear',
    icon: '🛑',
    unit: '%',
    min: 0,
    max: 100,
    baseline: 35,
    fluctuation: 1.5,
    normalRange: [0, 50],
    warningBands: [[50, 80]],
  },
  {
    key: 'vibration',
    label: 'Vibration Frequency',
    icon: '📳',
    unit: 'Hz',
    min: 0,
    max: 100,
    baseline: 25,
    fluctuation: 6,
    normalRange: [10, 40],
    warningBands: [[0, 10], [40, 60]],
  },
  {
    key: 'brakeFluidPressure',
    label: 'Brake Fluid Pressure',
    icon: '🧯',
    unit: 'PSI',
    min: 400,
    max: 1600,
    baseline: 1050,
    fluctuation: 40,
    normalRange: [950, 1150],
    warningBands: [[850, 950], [1150, 1250]],
  },
  {
    key: 'tirePressure',
    label: 'Tire Pressure',
    icon: '🛞',
    unit: 'PSI',
    min: 10,
    max: 50,
    baseline: 33,
    fluctuation: 3,
    normalRange: [30, 36],
    warningBands: [[26, 30], [36, 38]],
  },
  {
    key: 'batteryVoltage',
    label: 'Battery Voltage',
    icon: '🔋',
    unit: 'V',
    min: 9,
    max: 16,
    baseline: 12.6,
    fluctuation: 0.25,
    decimals: 2,
    normalRange: [12.4, 14.4],
    warningBands: [[11.8, 12.4], [14.4, 14.8]],
  },
  {
    key: 'transmissionFluidTemp',
    label: 'Transmission Fluid Temp',
    icon: '⚙️',
    unit: '°C',
    min: 0,
    max: 150,
    baseline: 80,
    fluctuation: 4,
    normalRange: [60, 95],
    warningBands: [[50, 60], [95, 110]],
  },
  {
    key: 'emissions',
    label: 'Emissions (CO)',
    icon: '🌫️',
    unit: 'ppm',
    min: 0,
    max: 1000,
    baseline: 180,
    fluctuation: 35,
    normalRange: [0, 300],
    warningBands: [[300, 500]],
  },
];

export const SENSOR_MAP = Object.fromEntries(SENSORS.map((s) => [s.key, s]));
